# Generated by Django 4.1.6 on 2024-07-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
